gui:
  border: rounded
  showBottomLine: false
  showPanelJumps: true
  nerdFontsVersion: "3"
  language: en
  theme:
    activeBorderColor:
      - "#f5a97f"
      - bold
    inactiveBorderColor:
      - "#5b6078"
    searchingActiveBorderColor:
      - "#f5a97f"
      - bold
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#494d64"
    cherryPickedCommitBgColor:
      - "#f0c6c6"
    cherryPickedCommitFgColor:
      - "#8aadf4"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: false
  merging:
    args: --no-ff
  pull:
    mode: rebase

os:
  editPreset: nvim

keybinding:
  universal:
    quit: q
    quit-alt1: <c-q>
    togglePanel: <tab>
    toggleRangeSelectInto: <space>
    undo: z
    redo: <c-z>
